name: Black Code Formatter

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Black
        run: pip install black==23.3.0

      - name: Run Black
        run: black --check .